---
title: "water-center_test"
output:
  pdf_document: default
    #template: single-page-abstract_template.tex
  word_document: default
  html_document: default
---
\documentclass[a4paper]{article}
%\usepackage{simplemargins}

%\usepackage[square]{natbib}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}

\begin{document}
\pagenumbering{gobble}

```{r setup, include = F}
# A Prefix nulling hook.

# Make sure to keep the default for normal processing.
default_output_hook <- knitr::knit_hooks$get("output")

# Output hooks handle normal R console output.
knitr::knit_hooks$set( output = function(x, options) {

  comment <- knitr::opts_current$get("comment")
  if( is.na(comment) ) comment <- ""
  can_null <- grepl( paste0( comment, "\\s*\\[\\d?\\]" ),
                     x, perl = TRUE)
  do_null <- isTRUE( knitr::opts_current$get("null_prefix") )
  if( can_null && do_null ) {
    # By default R print output aligns at the right brace.
    align_index <- regexpr( "\\]", x )[1] - 1
    # Two cases: start or newline
    re <- paste0( "^.{", align_index, "}\\]")
    rep <- comment
    x <- gsub( re, rep,  x )
    re <- paste0( "\\\n.{", align_index, "}\\]")
    rep <- paste0( "\n", comment )
    x <- gsub( re, rep,  x )
  }

  default_output_hook( x, options )

})

knitr::opts_template$set("kill_prefix"=list(comment=NA, null_prefix=TRUE))
knitr::opts_chunk$set("echo" = F, opts.label = "kill.prefix")
```

```{r set abstract file & author objects, include = F, warning = F, message = F}
meld <- read.csv("./TheAbstractSubmissions2018.csv")

first_author_name <- paste(meld$a, meld$b,sep = "")
MI = meld$MI; for(i in MI){
  if(is.na(MI[i]) == ""){
  }  else(MI == MI[i])
}
MI = gsub("[[:punct:]]", "", MI)#remove any '.' or other punctuation
author_name = stringr::str_to_title(paste(meld$a, MI, meld$b))#standardize the capitalization
title = meld[,'title']#grab titles
abstract = meld[,'abstract']#grab abstracts

first_coauthor = meld[,c( "g", "h")];second_coauthor = meld[,c("j", "k")]; third_coauthor = meld[, c("m", "n")];fourth_coauthor = meld[,c("p", "q")]; fifth_coauthor = meld[,c("s", "t")];sixth_coauthor= meld[,c("v", "w")]

coauthors = meld[,c("g", "h","j", "k","m", "n","p", "q","s", "t","v", "w")];coauthors$x = ""

names = list();z = c()
for (i in 1:length(author_name)){
 z[i] = min(which(apply(coauthors[i,], MARGIN = 2, ragtop::is.blank)))
if(z == 1){ names[[i]] = NULL  
} else(names[[i]] = coauthors[i,1:(z[i]-1)])
 }
 names[[1]][1:length(names[[1]])]
 
```
\Large
 \begin{center}
`r cat(as.character(droplevels(title[i])),"\n")`\\ 

\hspace{10pt}


```{r, null_prefix = TRUE, results = 'asis'}
for (i in 1:nrow(meld)){
cat(as.character(droplevels(title[i])),"\n")
 
cat(names[i]$g,"\n")

cat(abstract[i])
cat("\n\\newpage\n")

}
```
```{r results = 'asis', echo = F}
```

```{r author, echo = F, results='asis'}

#names = list()
#for (i in 1:length(author_name)){
# z = min(which(apply(coauthors[i,], MARGIN = 2, ragtop::is.blank)))
# `r print(x, size = 20)`

#names[i] = coauthors[i,1:as.numeric(z)];return(as.data.frame(unlist(names)))
#  }
 #print(paste(author_name[i]), as.character(z)),size = 16)
```


```{r abstract, echo = F, results = 'asis'}

#cat("\n\\newpage\n")
```
